---
driver:
  name: vagrant
  require_chef_omnibus: latest
  customize:
    memory: 2048

platforms:
- name: centos-6
  driver:
    box: chef/centos-6.6
- name: centos-7
  driver:
    box: chef/centos-7.1
- name: ubuntu-12.04
  driver:
    box: chef/ubuntu-12.04
- name: ubuntu-14.04
  driver:
    box: chef/ubuntu-14.04

provisioner:
  name: chef_zero
  attributes:
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true

suites:
- name: confluence-installer-mysql
  run_list:
  - recipe[java]
  - recipe[confluence]
  attributes:
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo
- name: confluence-installer-postgresql
  run_list:
  - recipe[java]
  - recipe[confluence]
  attributes:
    confluence:
      database:
        type: postgresql
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
