AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
  Exclude:
    - test/**/*
    - vendor/**/*
    - ruby/**/*

HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
ModuleLength:
  Enabled: false
MethodLength:
  Max: 30
