AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
  Exclude:
    - test/**
    - vendor/**
    - ruby/**

AlignParameters:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Encoding:
  Enabled: false
FileName:
  Enabled: false
HashSyntax:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
